src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $chambre;

    /**
     * @ORM\Column(type="integer")
     */
    private $pieces;

    /**
     * @ORM\Column(type="integer")
     */
    private $etage;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $solde = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    public function __construct()
    {
        $this->date_creation = new \DateTime();
    }

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug()
    {
         return (new Slugify)->slugify($this->titre);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getChambre(): ?int
    {
        return $this->chambre;
    }

    public function setChambre(int $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }

    public function getPieces(): ?int
    {
        return $this->pieces;
    }

    public function setPieces(int $pieces): self
    {
        $this->pieces = $pieces;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(int $etage): self
    {
        $this->etage = $etage;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormatPrix(): string
    {
        return number_format($this->prix, 0, '', ' ');
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getSolde(): ?bool
    {
        return $this->solde;
    }

    public function setSolde(bool $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{

    /**
     * @Route("/", name="home")
     */
    public function index(PropertyRepository $repository): Response
    {
        $properties = $repository->findLatest(); 
        return $this->render('pages/home.html.twig', [
            'properties' => $properties
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{

    /**
     * @var PropertyRepository
     */
    private $repository;
    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }
    /**
     * @Route("/biens", name="details.index")
     */
    public function index(): Response
    {
       /* $property = new Property();
        $property->setTitre('Biens N 1')
            ->setPrix(15000)
            ->setPieces(2)
            ->setChambre(1)
            ->setDescription("Chambre moderne situe au niveau de pk16")
            ->setEtage(1)
            ->setVille("Douala-Pk16")
            ->setSurface(30)
            ->setAdresse('Pk16');
        $em = $this->getDoctrine()->getManager();
        $em->persist($property);
        $em->flush();*/ 
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties'
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show($slug, $id): Response
    {
        $property = $this->repository->find($id);
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-primary bg-dark">
            <a class="navbar-brand" href="{{ path('home') }}">Agence TMP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if current_menu is defined and current_menu == 'properties' %}active{% endif %} " href="{{ path('details.index') }}">Consulter</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title 'Agence TMP' %}

{% block body %}
    <div class="jumbotron text-center">   
            <h1>Agence TMP</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto animi quibusdam nisi rerum veritatis consequuntur omnis tenetur, voluptatem consectetur veniam maiores, nemo recusandae nesciunt quis sapiente vel? Pariatur, nisi consectetur.</p>
    </div>  

    <div class="container">
        <h2>Les premiers biens de notre agence</h2>
        <div class="row flex">
            {% for property in properties %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-title">
                                <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.titre }}</a>
                                <p class="card-text">{{ property.ville }} </p>
                                <div class="text-primary" style="font-weight: bold; font-size: 2rem" >{{ property.formatPrix }} Fcfa</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens' %}

{% block body %}
        <div class="container mt-4">
            <h1>Voir tous nos biens</h1>
        </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.titre %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    photo
                </div>

                <div class="col-md-4">
                    <h1>{{ property.titre }}</h1>
                    <h2>{{ property.pieces }} pieces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formatPrix }} Fcfa</div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        

         <div class="row">
             <div class="col-md-8">
                 <h2>Caracteristiques</h2>
                 <table class="table table-striped">
                     <tr>
                         <td>Surface Habitable</td>
                         <td>{{ property.surface }} m²</td>
                     </tr>
                     <tr>
                         <td>Pieces</td>
                         <td>{{ property.pieces }}</td>
                     </tr>
                     <tr>
                         <td>Chambres</td>
                         <td>{{ property.chambre }}</td>
                     </tr>
                     <tr>
                         <td>Etage</td>
                         <td>{{ property.etage }}</td>
                     </tr>
                 </table>
             </div>
             <div class="col-md-4">
                 <h2>Specificites</h2>
                 <p>
                    {{ property.description | nl2br }}
                 </p>
             </div>
         </div>
    </div>
{% endblock %}